### ISSUE TITLE
Multiple video_editor binary packages

### ISSUE THREAD

**Issue by LeGoffMael** [LeGoffMael/video_editor#133]
To fix #129 kind of issues a solution would be do like `ffmpeg_kit`, publish multiple packages using different ffmpeg distribution

For example:
```yaml
video_editor: any
video_editor_min: any
video_editor_min_gpl: any
video_editor_full: any
video_editor_full_gpl: any
video_editor_https: any
# ... maybe more ?
```

check out [melos](https://docs.page/invertase/melos)
